---
title: "R Notebook"
output: html_notebook
---

When mapping the location of samples, we need to center the worldmap to the coordinates were the samples are from



```{r}
library(marmap)
library(tidyverse)
library(rgdal)
library(rnaturalearth)
library(mapdata)
library(metR)
library(raster)
```


## Start with the location of the samples

Change this accordingly to the project at hand. Make sure latitude and longitude columns are labelled `lat` and `lon`

```{r samples}

eDNA.samples <- read_csv("cleaned_CTD_stations.csv")

Selected.samples <- read_csv(here("Data", "plates.eDNA.csv"))



eDNA.samples %>% 
  separate(Station, into = c("Transect", "Stop"), remove = F) %>% 
  group_by(Transect, Date) %>% 
  summarise(xstart = max(lon),
            xend = min(lon),
            ystart = mean(lat),
            yend  = mean(lat)) %>% 
  mutate(MonthDay = paste(lubridate::month(Date, label = T), 
                          lubridate::day(Date), sep = "-")) -> Transects

named_pull <- function(x, values_from, names_from){
names.output<- pull(x, {{names_from}})
output <- pull(x, {{values_from}})
names(output)<- names.output
return(output)
}


# Get the coordinates

eDNA.samples %>% 
  summarise_at(c("lat", "lon"), .funs = list( Max = ~ round( max(.x) + 1,0) ,
                                              Min = ~ round( min(.x) - 1,0))) %>% pivot_longer(cols = everything(),names_to = "Corner",
                                                                                               values_to = "Coordinates") %>% named_pull(Coordinates, Corner) -> limits.for.map


```


```{r bathymetry}
b = getNOAA.bathy(lon1 = limits.for.map["lon_Max"],
                  lon2 = limits.for.map[ "lon_Min" ],
                  lat1 = limits.for.map["lat_Min"], 
                  lat2 = limits.for.map["lat_Max"], 
                  resolution = 1)

b <- fortify(b)
b



slope <- terrain(rasterFromXYZ(b, crs = "+proj=longlat +datum=WGS84 +no_defs"), opt = "slope")
str(slope)
as.data.frame(as(slope, "SpatialPixelsDataFrame")) -> slope
```

```{r}




base_map <- ne_countries(scale="large",returnclass="sf")
sf::st_crs(base_map)




ggplot(base_map) +
  
  geom_raster(data = b %>%  filter (z < 0),
              aes(x=x, y=y, fill=z)) + 

  geom_sf() +
  
  coord_sf(xlim=c(limits.for.map["lon_Min"], limits.for.map["lon_Max"]),ylim=c(limits.for.map["lat_Min"], limits.for.map["lat_Max"]),expand=F) +

  geom_contour(data = b %>%  filter (z < 0), 
               aes(x=x, y=y, z=z),
               breaks=c(  -50, -75),
               size=c(0.3),
               colour="grey")  +
  geom_text_contour (data = b %>%  filter (z < 0,y < 47), 
               aes(x=x, y=y,   z = z),
               breaks=c( -50, -75),
              
               colour="black")+
  theme_minimal() +
  guides(fill = guide_legend(title = "depth"))+
  xlab("") +
  ylab("")  -> base_plot


base_plot +
  geom_segment (data = Transects, aes (x = xstart, y = ystart,xend =  xend,yend =  yend, group = Transect)) +
  geom_point(data = eDNA.samples, aes(x= lon, y = lat), fill = "white", shape = 21, color = "black", size = 1) +
  geom_point(data = Selected.samples, aes(x= lon, y = lat), fill = "red", shape = 21, color = "black", size = 1)


base_plot +
  geom_point(data = eDNA.samples, aes(x= lon, y = lat), fill = "white", shape = 21, color = "black", size = 1) %>% 
  write_rds(here("Data", "base_plot_eDNA.rds"))
```

```{r}
ggplot(data = base_map)+
  geom_sf()+
   coord_sf(xlim=c(limits.for.map["lon_Min"], limits.for.map["lon_Max"]),ylim=c(limits.for.map["lat_Min"], limits.for.map["lat_Max"]),expand=F)
```

