---
title: "Dirichilet with error bars"
author: "Ramon Gallego"
date: "8/19/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dirichelet



```{r libraries, echo = F, message=F, warning=FALSE}
library(DirichletReg)
library(tidyverse)
library(broom)

```

## Dataset

Let's use the Arctic lake dataset

```{r pressure, echo=T}

ArcticLake

ArcticLake$prop <-DR_data(ArcticLake[,1:3]) 

```

## First model, linear

Fit the changes in percentages of soil composition as a function of depth

```{r}
lake1 <- DirichReg(prop ~ depth, ArcticLake)
lake1
coef(lake1)
```

And also fit them to a quadratic model

```{r}
lake2 <- update(lake1, . ~ . + I(depth^2) | . + I(depth^2) | . + I(depth^2))

anova(lake1, lake2)

summary(lake2)

lake3 <- DirichReg(prop ~ depth, ArcticLake, model = "alternative")
```

```{r}
predict(lake3, tibble(depth = 0:110), T,T,T) %>% 
  map(~ as_tibble(.x) %>%
  mutate(depth = 0:110)) -> predictions
```

## Predict 100 times and plot mean and sd

```{r lake2}

predict.many <- function(model, df){
  
  predict(model, df, T) %>% 
  as_tibble() %>% 
          bind_cols(df) %>%
    
    pivot_longer(-depth, names_to = "component", values_to = "value") 
}

map(1:1000, ~predict.many( lake2, tb)) %>% 
  bind_rows(.id = "iteration") %>% 
  group_by(depth, component) %>% 
  summarise(mean.mu = mean(value),
            sd.mu   = sd(value)) -> summarised.output
  
summarised.output %>% 
ggplot(aes(x = depth,
             y = mean.mu))+
  geom_pointrange(aes(color = component, ymin = mean.mu - sd.mu, ymax = mean.mu +sd.mu))
```


```{r}
tb <- tibble(depth = 0:110)
predict(lake2, tb, T,T,T) %>% 
  map(~ as_tibble(.x) %>%
  bind_cols(tb)) -> predictions

predictions[1:2] %>% 
  map(~.x %>%
         rename(sand =1, silt = 2, clay = 3) %>% 
        pivot_longer(-depth, names_to = "variable", values_to = "var2")
      ) %>% 
  bind_rows(.id = "var3") %>% 
  # pivot_wider(names_from = var3, values_from = var2) %>% 
  ggplot(aes(x = depth, color = variable))+
  geom_point(aes(y = var2)) +
  facet_wrap(~var3, nrow =1, scales ="free_y")

predictions[[3]] %>% 
  rename(sand =1, silt = 2, clay = 3) %>% 
  # mutate(variable = "mu") %>% 
  pivot_longer(-depth, names_to = "variable", values_to = "mu") %>% 
  ggplot(aes(x = depth, y = mu, color = variable)) +
  geom_line() +
  lims(y = c(0,1))

as_tibble(predict(lake2, tibble(depth = seq(0,110, by = 1)))) %>% 
  rename(sand =1, silt = 2, clay = 3) %>% 
  mutate(depth = 0:110) -> mean.predictions

predictions[3]
```


```{r}
residuals(lake2)
confint(lake2)
confint(lake2, exp = T)
```

