---
title: "R Notebook"
output: html_notebook
---

When mapping the location of samples, we need to center the worldmap to the coordinates were the samples are from



```{r}
library(marmap)
library(tidyverse)
library(rgdal)
library(rnaturalearth)
library(mapdata)
library(metR)
library(raster)
```


## Start with the location of the samples

Change this accordingly to the project at hand. Make sure latitude and longitude columns are labelled `lat` and `lon`

```{r samples}

eDNA.samples <- read_csv("cleaned_CTD_stations.csv")

named_pull <- function(x, values_from, names_from){
names.output<- pull(x, {{names_from}})
output <- pull(x, {{values_from}})
names(output)<- names.output
return(output)
}


# Get the coordinates

# Get the limits for the map
named_pull <- function(x, values_from, names_from){
names.output<- pull(x, {{names_from}})
output <- pull(x, {{values_from}})
names(output)<- names.output
return(output)
}


# Get the coordinates

metadata %>% 
  summarise(across(c("lat", "lon"), .fns = list( Max = ~ round( max(.x, na.rm = T) + 1,0) ,
                                              Min = ~ round( min(.x, na.rm = T) - 1,0)))) %>% pivot_longer(cols = everything(),names_to = "Corner",
                                                                                               values_to = "Coordinates") %>% named_pull(Coordinates, Corner)-> limits.for.map


# Bathymetry
b = getNOAA.bathy(lon1 = limits.for.map["lon_Max"],
                  lon2 = limits.for.map[ "lon_Min" ],
                  lat1 = limits.for.map["lat_Min"], 
                  lat2 = limits.for.map["lat_Max"], 
                  resolution = 1)

b <- fortify(b)

# Slope 

slope <- terrain(rasterFromXYZ(b, crs = "+proj=longlat +datum=WGS84 +no_defs"), opt = "slope")
str(slope)
as.data.frame(as(slope, "SpatialPixelsDataFrame")) -> slope

# Get the basemap

base_map <- ne_countries(scale="large",returnclass="sf")
sf::st_crs(base_map)


# And all together for future use

ggplot(base_map) +
  
  geom_raster(data = b %>%  filter (z < 0),
              aes(x=x, y=y, fill=z)) + 

  geom_sf() +
  
  coord_sf(xlim=c(limits.for.map["lon_Min"], limits.for.map["lon_Max"]),
           ylim=c(limits.for.map["lat_Min"], limits.for.map["lat_Max"]),expand=F) +

  geom_contour(data = b %>%  filter (z < 0), 
               aes(x=x, y=y, z=z),
               breaks=c(  -50, -200),
               size=c(0.3),
               colour="grey")  +
  geom_text_contour (data = b %>%  filter (z < 0,y < 47), 
               aes(x=x, y=y,   z = z),
               breaks=c( -50, -200),
              
               colour="black")+
  theme_minimal() +
  xlab("") +
  ylab("") +
  labs(fill = "depth") -> base_plot

base_plot %>% write_rds(here("Data/Hake_map.rds"))


base_plot +
  geom_segment (data = Transects, aes (x = xstart, y = ystart,xend =  xend,yend =  yend, group = Transect)) +
  geom_text(data = Transects, aes (x =   xend - 0.25,y  =  yend, label = Transect), color = "yellow", fontface = "bold")
```

```{r}
ggplot(data = base_map)+
  geom_sf()+
  coord_sf(xlim=c(limits.for.map["lon_Max"], limits.for.map["lon_Min"]),ylim=c(limits.for.map["lat_Max"], limits.for.map["lat_Min"]),expand=F)
```

